<a href="https://colab.research.google.com/github/manshi25/Sentiment-Analysis/blob/main/Sentiment_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install ipython-autotime
%load_ext autotime

time: 870 µs (started: 2021-08-16 15:19:16 +00:00)


In [2]:
!pip install vaderSentiment

time: 2.92 s (started: 2021-08-16 15:19:16 +00:00)


In [3]:
from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer
vs=SentimentIntensityAnalyzer()

time: 16.7 ms (started: 2021-08-16 15:19:19 +00:00)


In [4]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import numpy as np
import os

time: 80.4 ms (started: 2021-08-16 15:19:19 +00:00)


In [5]:
df=pd.read_csv('https://raw.githubusercontent.com/bhukyavamshirathod/Sentimental-Analysis/main/Train.csv')
df

id  label                                              tweet
0         1      0   @user when a father is dysfunctional and is s...
1         2      0  @user @user thanks for #lyft credit i can't us...
2         3      0                                bihday your majesty
3         4      0  #model   i love u take with u all the time in ...
4         5      0             factsguide: society now    #motivation
...     ...    ...                                                ...
9995   9996      0   @user my routine is out of whack! evening wal...
9996   9997      0  i'm dead but still happy #poledance #madrid ##...
9997   9998      0   ↝ #united kingdom claimant count rate up to...
9998   9999      0  rip my friend 😢😢 #shocked   #dismay #hea...
9999  10000      0  how to open... your  , loving hea  #thursdayth...

[10000 rows x 3 columns]

time: 352 ms (started: 2021-08-16 15:19:19 +00:00)


In [6]:
df.head()

id  label                                              tweet
0   1      0   @user when a father is dysfunctional and is s...
1   2      0  @user @user thanks for #lyft credit i can't us...
2   3      0                                bihday your majesty
3   4      0  #model   i love u take with u all the time in ...
4   5      0             factsguide: society now    #motivation

time: 16.1 ms (started: 2021-08-16 15:19:19 +00:00)


In [7]:
import nltk
nltk.download('stopwords')
stopword_list=nltk.corpus.stopwords.words('english')
negative_words=['no','not',"don't","aren't","couldn't","didn't","doesn't","hadn't","hasn't","haven't","isn't","mightn't","mustn't","needn't","shouldn't","wasn't","weren't","won't","wouldn't"]
for negative_word in negative_words:
  stopword_list.remove(negative_word)

len(stopword_list)

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


160

time: 631 ms (started: 2021-08-16 15:19:19 +00:00)


In [8]:
stopword_list

['i',
 'me',
 'my',
 'myself',
 'we',
 'our',
 'ours',
 'ourselves',
 'you',
 "you're",
 "you've",
 "you'll",
 "you'd",
 'your',
 'yours',
 'yourself',
 'yourselves',
 'he',
 'him',
 'his',
 'himself',
 'she',
 "she's",
 'her',
 'hers',
 'herself',
 'it',
 "it's",
 'its',
 'itself',
 'they',
 'them',
 'their',
 'theirs',
 'themselves',
 'what',
 'which',
 'who',
 'whom',
 'this',
 'that',
 "that'll",
 'these',
 'those',
 'am',
 'is',
 'are',
 'was',
 'were',
 'be',
 'been',
 'being',
 'have',
 'has',
 'had',
 'having',
 'do',
 'does',
 'did',
 'doing',
 'a',
 'an',
 'the',
 'and',
 'but',
 'if',
 'or',
 'because',
 'as',
 'until',
 'while',
 'of',
 'at',
 'by',
 'for',
 'with',
 'about',
 'against',
 'between',
 'into',
 'through',
 'during',
 'before',
 'after',
 'above',
 'below',
 'to',
 'from',
 'up',
 'down',
 'in',
 'out',
 'on',
 'off',
 'over',
 'under',
 'again',
 'further',
 'then',
 'once',
 'here',
 'there',
 'when',
 'where',
 'why',
 'how',
 'all',
 'any',
 'both',
 'each

time: 12.9 ms (started: 2021-08-16 15:19:20 +00:00)


In [9]:
# removing html tag
def html_tag(text):
  soup=BeautifulSoup(text,"html.parser")
  new_text=soup.get_text()
  return new_text

time: 938 µs (started: 2021-08-16 15:19:20 +00:00)


In [10]:
# expand contractions
!pip install contractions
import contractions
def con(text):
  expand=contractions.fix(text)
  return expand

time: 2.95 s (started: 2021-08-16 15:19:20 +00:00)


In [11]:
# removal of special character
import re
def remove_sp(text):
  pattern=r'[^A-Za-z0-9\s]'
  text=re.sub(pattern,'',text)
  return text

time: 1.06 ms (started: 2021-08-16 15:19:23 +00:00)


In [12]:
# remove stop words
from nltk.tokenize.toktok import ToktokTokenizer
tokenizer=ToktokTokenizer()

def remove_stop_words(text):
  tokens=tokenizer.tokenize(text)
  tokens=[token.strip() for token in tokens]
  filtered_tokens=[token for token in tokens if token not in stopword_list]
  filtered_text=' '.join(filtered_tokens)
  return filtered_text

time: 2.14 ms (started: 2021-08-16 15:19:23 +00:00)


In [13]:
df.tweet=df.tweet.apply(lambda x:x.lower())
df.tweet=df.tweet.apply(html_tag)
df.tweet=df.tweet.apply(con)
df.tweet=df.tweet.apply(remove_sp)
df.tweet=df.tweet.apply(remove_stop_words)

time: 1.47 s (started: 2021-08-16 15:19:23 +00:00)


In [14]:
df.head()

id  label                                              tweet
0   1      0  user father dysfunctional selfish drags kids d...
1   2      0  user user thanks lyft credit cannot use not of...
2   3      0                                     bihday majesty
3   4      0                            model love take time ur
4   5      0                      factsguide society motivation

time: 17 ms (started: 2021-08-16 15:19:24 +00:00)


In [15]:
#df['compound']=df['news_article'].apply(lambda x: vs.polarity_scores(x)['compound'])
df['compound']=df['tweet'].apply(lambda x: vs.polarity_scores(x)['compound'])

time: 804 ms (started: 2021-08-16 15:19:25 +00:00)


In [16]:
conditions = [
    (df['compound'] >= 0.05),
    (df['compound'] > -0.05) & (df['compound'] < 0.05),
    (df['compound'] <= -0.05)
    ]

# create a list of the values we want to assign for each condition
values = ['Positive', 'Neutral', 'Negative']

# create a new column and use np.select to assign values to it using our lists as arguments
df['tier'] = np.select(conditions, values)

# display updated DataFrame
df

id  label  ... compound      tier
0         1      0  ...  -0.7650  Negative
1         2      0  ...   0.6705  Positive
2         3      0  ...   0.0000   Neutral
3         4      0  ...   0.6369  Positive
4         5      0  ...   0.3400  Positive
...     ...    ...  ...      ...       ...
9995   9996      0  ...   0.5423  Positive
9996   9997      0  ...   0.1280  Positive
9997   9998      0  ...   0.4215  Positive
9998   9999      0  ...  -0.7096  Negative
9999  10000      0  ...   0.5994  Positive

[10000 rows x 5 columns]

time: 34.9 ms (started: 2021-08-16 15:19:25 +00:00)


In [17]:
x = df.iloc[:,2].values
y = df.iloc[:,-1].values

time: 1.79 ms (started: 2021-08-16 15:19:25 +00:00)


In [18]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.3,random_state = 0,stratify = y)
x_train.shape

(7000,)

time: 26.6 ms (started: 2021-08-16 15:19:25 +00:00)


In [19]:
np.unique(y_train,return_counts=True)

(array(['Negative', 'Neutral', 'Positive'], dtype=object),
 array([1460, 1903, 3637]))

time: 12 ms (started: 2021-08-16 15:19:25 +00:00)


In [20]:
np.unique(y_test,return_counts=True)

(array(['Negative', 'Neutral', 'Positive'], dtype=object),
 array([ 626,  816, 1558]))

time: 9.14 ms (started: 2021-08-16 15:19:25 +00:00)


In [21]:
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.svm import SVC

time: 3.15 ms (started: 2021-08-16 15:19:25 +00:00)


In [22]:
text_model = Pipeline([('tfidf',TfidfVectorizer()),('model',SVC(C=1.6,kernel='linear'))])

time: 1.71 ms (started: 2021-08-16 15:19:25 +00:00)


In [23]:
text_model.fit(x_train,y_train)

Pipeline(memory=None,
         steps=[('tfidf',
                 TfidfVectorizer(analyzer='word', binary=False,
                                 decode_error='strict',
                                 dtype=<class 'numpy.float64'>,
                                 encoding='utf-8', input='content',
                                 lowercase=True, max_df=1.0, max_features=None,
                                 min_df=1, ngram_range=(1, 1), norm='l2',
                                 preprocessor=None, smooth_idf=True,
                                 stop_words=None, strip_accents=None,
                                 sublinear_tf=False,
                                 token_pattern='(?u)\\b\\w\\w+\\b',
                                 tokenizer=None, use_idf=True,
                                 vocabulary=None)),
                ('model',
                 SVC(C=1.6, break_ties=False, cache_size=200, class_weight=None,
                     coef0=0.0, decision_function_shape='ovr', d

time: 5.64 s (started: 2021-08-16 15:19:25 +00:00)


In [24]:
y_pred = text_model.predict(x_test)
y_pred

array(['Positive', 'Positive', 'Neutral', ..., 'Negative', 'Positive',
       'Neutral'], dtype=object)

time: 1.19 s (started: 2021-08-16 15:19:31 +00:00)


In [25]:
np.unique(y_pred,return_counts=True)

(array(['Negative', 'Neutral', 'Positive'], dtype=object),
 array([ 596,  842, 1562]))

time: 6.69 ms (started: 2021-08-16 15:19:32 +00:00)


In [26]:
y_test

array(['Positive', 'Neutral', 'Neutral', ..., 'Negative', 'Positive',
       'Neutral'], dtype=object)

time: 3.1 ms (started: 2021-08-16 15:19:32 +00:00)


In [27]:
# Evaluation
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix
accuracy_score(y_pred,y_test)

0.7936666666666666

time: 10.7 ms (started: 2021-08-16 15:19:32 +00:00)


In [28]:
confusion_matrix(y_pred,y_test)

array([[ 416,   74,  106],
       [ 101,  627,  114],
       [ 109,  115, 1338]])

time: 24.7 ms (started: 2021-08-16 15:19:32 +00:00)


In [29]:
print(classification_report(y_pred,y_test))

              precision    recall  f1-score   support

    Negative       0.66      0.70      0.68       596
     Neutral       0.77      0.74      0.76       842
    Positive       0.86      0.86      0.86      1562

    accuracy                           0.79      3000
   macro avg       0.76      0.77      0.76      3000
weighted avg       0.79      0.79      0.79      3000

time: 107 ms (started: 2021-08-16 15:19:32 +00:00)


In [30]:
text_model.predict(["#people aren't protesting #trump because a #republican not every on e won never hw is dumbo kjkjwe @#$%^&*€¦ "])

array(['Positive'], dtype=object)

time: 8.48 ms (started: 2021-08-16 15:19:33 +00:00)


In [31]:
!pip install streamlit
!pip install pyngrok==4.1.1
from pyngrok import ngrok

time: 6.29 s (started: 2021-08-16 15:19:33 +00:00)


In [35]:
%%writefile app.py
import streamlit as st
import requests
from bs4 import BeautifulSoup
import pandas as pd
import numpy as np
import os
import nltk
nltk.download('stopwords')
stopword_list=nltk.corpus.stopwords.words('english')
stopword_list.remove('no')
stopword_list.remove('not')

# remove html tag
def html_tag(text):
  soup=BeautifulSoup(text,"html.parser")
  new_text=soup.get_text()
  return new_text

# !pip install contractions
import contractions
def con(text):
  expand=contractions.fix(text)
  return expand

# removal of special character
import re
def remove_sp(text):
  pattern=r'[^A-Za-z0-9\s]'
  text=re.sub(pattern,'',text)
  return text


# remove stop words
from nltk.tokenize.toktok import ToktokTokenizer
tokenizer=ToktokTokenizer()

def remove_stop_words(text):
  tokens=tokenizer.tokenize(text)
  tokens=[token.strip() for token in tokens]
  filtered_tokens=[token for token in tokens if token not in stopword_list]
  filtered_text=' '.join(filtered_tokens)
  return filtered_text

st.title("Tweet's Sentiment Analysis")

df = pd.read_csv('https://raw.githubusercontent.com/bhukyavamshirathod/Sentimental-Analysis/main/Train.csv')

df.tweet=df.tweet.apply(lambda x:x.lower())
df.tweet=df.tweet.apply(html_tag)
df.tweet=df.tweet.apply(con)
df.tweet=df.tweet.apply(remove_sp)
df.tweet=df.tweet.apply(remove_stop_words)

from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer
vs=SentimentIntensityAnalyzer()

df['compound']=df['tweet'].apply(lambda x: vs.polarity_scores(x)['compound'])

conditions = [
    (df['compound'] >= 0.05),
    (df['compound'] > -0.05) & (df['compound'] < 0.05),
    (df['compound'] <= -0.05)
    ]

# create a list of the values we want to assign for each condition
values = ['Positive', 'Neutral', 'Negative']

# create a new column and use np.select to assign values to it using our lists as arguments
df['tier'] = np.select(conditions, values)

x = df.iloc[:,2].values
y = df.iloc[:,-1].values

from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.svm import SVC
text_model = Pipeline([('tfidf',TfidfVectorizer()),('model',SVC())]) 
text_model.fit(x,y)
select = st.text_input('Enter your message')

if(st.markdown(
    '<span class="badge badge-pill badge-success"> Badge </span>',
    unsafe_allow_html=True
)):
  op = text_model.predict([select])
  ans=op[0]

  if ans == 'Positive':
    st.success("Positive 🙂")
  if ans == 'Negative':
    st.error("Negative 😠")
  if ans== 'Neutral':
    st.warning("Neutral 😐") 

Overwriting app.py
time: 3.27 ms (started: 2021-08-16 15:25:03 +00:00)


In [36]:
!nohup streamlit run app.py &
url = ngrok.connect(port='8501')
url

nohup: appending output to 'nohup.out'


'http://a53ba4acfce0.ngrok.io'

time: 2.12 s (started: 2021-08-16 15:25:26 +00:00)
